### ISSUE TITLE
Run/Walk Activity Tracker

### ISSUE THREAD

**Issue by fincharry27** [JamesGit1/ProjectRunning#18]
- [ ] Start button starts the activity 
- [ ] App tracks elapsed time, distance, songs listened to, route. 
- [ ] In live time app displays time, distance 
- [ ] End button ends the activity 
- [ ] Image is generated containing route and songs played at each section ('Grooves'?) 
- [ ] Run is added to activity history
